title: Work journal
author: supersai007
email: supersai.007@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Journal on day to day changes in the work.

# social links
twitter_username: supersai007 # DO NOT include the @ character, or else the build will fail!
github_username:  supersai007 # DO NOT include the @ character, or else the build will fail!

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
